### ISSUE TITLE
[ API => panel ] < 2020-11-23 11:20:25 > ( ERROR - Wraith `All` not found! ) | <Command>

### ISSUE THREAD

**Issue by Metaspl01t-006** [TR-SLimey/wraith#3]

**Comment by TR-SLimey** [comment]
Can you provide some more context? For example z version and what you were attempting to do?

**Comment by TR-SLimey** [comment]
Nevermind, having looked at it while looking into one of your other issues, I realised what you mean. I think this feature might not have been implemented yet, when I stopped working on v3.0.0, so I'm afraid you'll have to select individually for now, like so:
![image](https://user-images.githubusercontent.com/37966924/100011667-f78fb980-2dc9-11eb-9e14-ffe73c41d999.png)
I realise v3 is neither the most user-friendly nor particularly robust, but hopefully when I get more time to release a v4, it'll be much better, since v3 was flawed from the start.
